services:
  - type: web
    name: whatsaly
    runtime: docker
    branch: master
    plan: hobby
    repo: https://github.com/astrox11/Whatsaly
    healthCheckPath: /
    buildCommand: bun install
    startCommand: bun run start

    envVars:
      - key: BOT_NAME
        sync: false
      - key: API_PORT
        sync: false
      - key: API_HOST
        sync: false
      - key: DEBUG
        sync: false
